import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import CategoryItem from '../components/CategoryItem'
import React, {useState} from 'react'

export async function getStaticProps() {
  // const res = await fetch('http://192.168.0.103:3000/categories');
  const res = await fetch('http://localhost:3000/categories');
  const categories = await res.json();
  return {
    props: {
      categories
    }
  }
}


export default function Home({ categories }) {

  const [cats, setCats] = useState()
  const [toAdd, setToAdd] = useState("")

  !cats ? setCats(categories) : null

  const handleClick = event => {

    let name = event.target.name
    let action = event.target.type

    console.log(name + " " + action)
    manageCategories(name, action)
  }

  const handleKeyup = () => {

  }

  const updateAdd = event => {

  }


  const updateCategoriesList = (name, action) => {
    console.log(cats[name])
    let categoriesToUpdate = cats
    
    action == "POST" ? categoriesToUpdate.push(name) : null 
    action == "DELETE" ? delete categoriesToUpdate[name] : null
    setCats(categoriesToUpdate)
    setToAdd("")
    window.location.reload()
  }


  const manageCategories = async (name, action) => {
    const res = await fetch ('http://localhost:3000/categories/', {
            method: action,
            body: JSON.stringify({
              name: `${name}`
            }),
            headers: {
                'Content-type': 'application/json'
            }
    })
    const confirmation = await res.json()
    console.log(confirmation)
    res.status < 300 ? updateCategoriesList(name, action) : console.error("Could not fulfill request")
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Rob's Recommender</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <a href="https://github.com/mirado1155">Recommender!</a>
        </h1>

        <p className={styles.description}>
          Click a category below to view, or add a new one here:
          <input type="text"></input>
          {/* <code className={styles.code}>pages/index.js</code> */}
        </p>

        <div className={styles.grid}>
          {Object.keys(categories).map((category) => (
            <CategoryItem category={category} handler={handleClick}></CategoryItem>
          ))}
        </div>
        
      </main>

      <footer className={styles.footer}>
        <a href="#">&copy; Robert Adams 2021</a>
      </footer>
    </div>
  )
}
