import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export async function getStaticProps() {
  const res = await fetch('http://192.168.0.103:3000/categories');
  const categories = await res.json();
  return {
    props: {
      categories
    },
  }
}



export default function Home({ categories }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://github.com/mirado1155">Rob's Recommender!</a>
        </h1>

        <p className={styles.description}>
          Click a category below to view, or add a new one here:
          <input type="text"></input>
          {/* <code className={styles.code}>pages/index.js</code> */}
        </p>

        <div className={styles.grid}>

          {Object.keys(categories).map((category) => (
            <a href="#" className={styles.card}>
              <h2>{category}</h2>
            </a>
          ))}

        </div>
      </main>

      <footer className={styles.footer}>
        <a href="#">&copy; Robert Adams 2021</a>
      </footer>
    </div>
  )
}
